name: 'Chatwork API Upload Room File Action'
description: 'Chatwork APIでチャットルームにファイルをアップロードする'
author: 'kentanakae'

inputs:
  api_token:
    description: 'Chatwork API トークン'
    required: true
  room_id:
    description: 'チャットルームのID'
    required: true
  file:
    description: 'アップロードするファイルのパス'
    required: true
  message:
    description: 'ファイルと一緒に送信するメッセージ'
    required: false
    default: ''

outputs:
  status_code:
    description: 'HTTPステータスコード'
    value: ${{ steps.api-call.outputs.status_code }}
  response:
    description: 'APIレスポンス'
    value: ${{ steps.api-call.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Upload room file API
      id: api-call
      uses: kentanakae/chatwork-api-actions/client@v1
      with:
        api_token: ${{ inputs.api_token }}
        endpoint: /rooms/${{ inputs.room_id }}/files
        method: POST
        params: |
          --form "file=@${{ inputs.file }}"
          --form "message=${{ inputs.message }}"
