name: 'Chatwork API Get Room Files Action'
description: 'Chatwork APIでチャットルームのファイル一覧を取得する'
author: 'kentanakae'

inputs:
  api_token:
    description: 'Chatwork API トークン'
    required: true
  room_id:
    description: 'チャットルームのID'
    required: true
  account_id:
    description: 'アップロードしたユーザーのアカウントID'
    required: false

outputs:
  status_code:
    description: 'HTTPステータスコード'
    value: ${{ steps.api-call.outputs.status_code }}
  response:
    description: 'APIレスポンス'
    value: ${{ steps.api-call.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Get room files API
      id: api-call
      uses: kentanakae/chatwork-api-actions/client@v1
      with:
        api_token: ${{ inputs.api_token }}
        endpoint: /rooms/${{ inputs.room_id }}/files?account_id=${{ inputs.account_id }}
        method: GET
