name: 'Chatwork API Create Room Task Action'
description: 'Chatwork APIでチャットルームにタスクを作成する'
author: 'kentanakae'

inputs:
  api_token:
    description: 'Chatwork API トークン'
    required: true
  room_id:
    description: 'チャットルームのID'
    required: true
  body:
    description: 'タスクの内容'
    required: true
  to_ids:
    description: 'タスクの担当者のアカウントIDリスト（カンマ区切り）'
    required: true
  limit:
    description: 'タスクの期限（Unix時間形式のタイムスタンプ）'
    required: false
  limit_type:
    description: 'タスク期限の種別（date:日付, time:時間）'
    required: false

outputs:
  status_code:
    description: 'HTTPステータスコード'
    value: ${{ steps.api-call.outputs.status_code }}
  response:
    description: 'APIレスポンス'
    value: ${{ steps.api-call.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Encode task body
      id: encode-body
      shell: bash
      run: |
        ENCODED_BODY=$(echo '${{ inputs.body }}' | jq -sRr @uri)
        echo "encoded_body=$ENCODED_BODY" >> $GITHUB_OUTPUT

    - name: Create task API
      id: api-call
      uses: kentanakae/chatwork-api-actions/client@v1
      with:
        api_token: ${{ inputs.api_token }}
        endpoint: /rooms/${{ inputs.room_id }}/tasks
        method: POST
        params: |
          --header "content-type: application/x-www-form-urlencoded"
          --data "body=${{ steps.encode-body.outputs.encoded_body }}&to_ids=${{ inputs.to_ids }}&limit=${{ inputs.limit }}&limit_type=${{ inputs.limit_type }}"
