name: 'Chatwork API Send Message Action'
description: 'Chatwork APIでメッセージを送信する'
author: 'kentanakae'

inputs:
  api_token:
    description: 'Chatwork API トークン'
    required: true
  room_id:
    description: '送信先のルームID'
    required: true
  body:
    description: '送信するメッセージ'
    required: true
  self_unread:
    description: '自分から見て未読にするか'
    required: false
    default: '0'

outputs:
  status_code:
    description: 'HTTPステータスコード'
    value: ${{ steps.api-call.outputs.status_code }}
  response:
    description: 'APIレスポンス'
    value: ${{ steps.api-call.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Send message API
      id: api-call
      uses: kentanakae/chatwork-api-actions/client@v1
      with:
        api_token: ${{ inputs.api_token }}
        endpoint: /rooms/${{ inputs.room_id }}/messages
        method: POST
        params: |
          --header "content-type: application/x-www-form-urlencoded"
          --data "body=${{ inputs.body }}&self_unread=${{ inputs.self_unread }}"
