name: 'Chatwork API Update Room Link Action'
description: 'Chatwork APIでチャットルームの招待リンクを作成・更新する'
author: 'kentanakae'

inputs:
  api_token:
    description: 'Chatwork API トークン'
    required: true
  room_id:
    description: 'チャットルームのID'
    required: true
  code:
    description: '招待リンクのパスワード'
    required: false
  description:
    description: '招待リンクの説明文'
    required: false
  need_acceptance:
    description: '招待を承認制にするか（0:承認制にしない, 1:承認制にする）'
    required: false
    default: '0'

outputs:
  status_code:
    description: 'HTTPステータスコード'
    value: ${{ steps.api-call.outputs.status_code }}
  response:
    description: 'APIレスポンス'
    value: ${{ steps.api-call.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Update room link API
      id: api-call
      uses: kentanakae/chatwork-api-actions/client@v1
      with:
        api_token: ${{ inputs.api_token }}
        endpoint: /rooms/${{ inputs.room_id }}/link
        method: PUT
        params: |
          --header "content-type: application/x-www-form-urlencoded"
          --data "code=${{ inputs.code }}&description=${{ inputs.description }}&need_acceptance=${{ inputs.need_acceptance }}"
