name: "Chatwork API Update Room Members Action"
description: "Chatwork APIでチャットルームのメンバーを更新する"
author: "kentanakae"

inputs:
  api_token:
    description: "Chatwork API トークン"
    required: true
  room_id:
    description: "チャットルームのID"
    required: true
  members_admin_ids:
    description: "管理者権限を持つユーザーのアカウントIDリスト（カンマ区切り）"
    required: true
  members_member_ids:
    description: "メンバー権限を持つユーザーのアカウントIDリスト（カンマ区切り）"
    required: false
    default: ""
  members_readonly_ids:
    description: "閲覧のみ権限を持つユーザーのアカウントIDリスト（カンマ区切り）"
    required: false
    default: ""

outputs:
  status_code:
    description: "HTTPステータスコード"
    value: ${{ steps.api-call.outputs.status_code }}
  response:
    description: "APIレスポンス"
    value: ${{ steps.api-call.outputs.response }}

runs:
  using: "composite"
  steps:
    - name: "Update room members API"
      id: "api-call"
      uses: kentanakae/chatwork-api-actions/client@v1
      with:
        api_token: ${{ inputs.api_token }}
        endpoint: /rooms/${{ inputs.room_id }}/members
        method: PUT
        params: |
          --header "content-type: application/x-www-form-urlencoded"
          --data "members_admin_ids=${{ inputs.members_admin_ids }}&members_member_ids=${{ inputs.members_member_ids }}&members_readonly_ids=${{ inputs.members_readonly_ids }}"
