name: 'Chatwork API Get Room Messages Action'
description: 'Chatwork APIでチャットルームのメッセージ一覧を取得する'
author: 'kentanakae'

inputs:
  api_token:
    description: 'Chatwork API トークン'
    required: true
  room_id:
    description: 'チャットルームのID'
    required: true
  force:
    description: '最新の100件を取得するか（0:現在未取得のメッセージのみ, 1:最新の100件取得）'
    required: false
    default: '0'

outputs:
  status_code:
    description: 'HTTPステータスコード'
    value: ${{ steps.api-call.outputs.status_code }}
  response:
    description: 'APIレスポンス'
    value: ${{ steps.api-call.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Get room messages API
      id: api-call
      uses: kentanakae/chatwork-api-actions/client@v1
      with:
        api_token: ${{ inputs.api_token }}
        endpoint: /rooms/${{ inputs.room_id }}/messages?force=${{ inputs.force }}
        method: GET
