name: 'Chatwork API Get Room File Action'
description: 'Chatwork APIで特定のファイル情報を取得する'
author: 'kentanakae'

inputs:
  api_token:
    description: 'Chatwork API トークン'
    required: true
  room_id:
    description: 'チャットルームのID'
    required: true
  file_id:
    description: 'ファイルのID'
    required: true
  create_download_url:
    description: 'ダウンロードリンクを生成するか（0:生成しない, 1:生成する）'
    required: false
    default: '1'

outputs:
  status_code:
    description: 'HTTPステータスコード'
    value: ${{ steps.api-call.outputs.status_code }}
  response:
    description: 'APIレスポンス'
    value: ${{ steps.api-call.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Get room file API
      id: api-call
      uses: kentanakae/chatwork-api-actions/client@v1
      with:
        api_token: ${{ inputs.api_token }}
        endpoint: /rooms/${{ inputs.room_id }}/files/${{ inputs.file_id }}?create_download_url=${{ inputs.create_download_url }}
        method: GET
