name: 'Chatwork API Delete Room Action'
description: 'Chatwork APIでチャットルームを削除（退室）する'
author: 'kentanakae'

inputs:
  api_token:
    description: 'Chatwork API トークン'
    required: true
  room_id:
    description: 'チャットルームのID'
    required: true
  action_type:
    description: '退室方法（leave, delete）'
    required: true

outputs:
  status_code:
    description: 'HTTPステータスコード'
    value: ${{ steps.api-call.outputs.status_code }}
  response:
    description: 'APIレスポンス'
    value: ${{ steps.api-call.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Delete room API
      id: api-call
      uses: kentanakae/chatwork-api-actions/client@v1
      with:
        api_token: ${{ inputs.api_token }}
        endpoint: /rooms/${{ inputs.room_id }}
        method: DELETE
        params: |
          --header "content-type: application/x-www-form-urlencoded"
          --data "action_type=${{ inputs.action_type }}"
